# Generated by Django 5.1 on 2024-09-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyoubo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='type',
            field=models.CharField(choices=[('mustitem', '必需品'), ('notmustitem', '娯楽品')], max_length=30, verbose_name='type'),
        ),
    ]
